name: Main 

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    name: cargo test
    env:
      CARGO: cargo
      TARGET:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - linux-stable
        - linux-32bit-stable
        - linux-beta
        - linux-nightly
        - macos-stable
        - win-msvc-stable
        - win-gnu-stable
        include:
        - build: linux-stable
          os: ubuntu-latest
          rust: stable
        - build: linux-32bit-stable
          os: ubuntu-latest
          rust: stable
          target: i686-unknown-linux-gnu
        - build: linux-beta
          os: ubuntu-latest
          rust: beta
        - build: linux-nightly
          os: ubuntu-latest
          rust: nightly
        - build: macos-stable
          os: macos-latest
          rust: stable
        - build: win-msvc-stable
          os: windows-latest
          rust: stable
        - build: win-gnu-stable
          os: windows-latest
          rust: stable-x86_64-gnu
    steps:

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Use Cross
      if: matrix.target != ''
      run: |
        cargo install --bins --git https://github.com/cross-rs/cross --tag v0.2.1
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET=--target ${{ matrix.target }}" >> $GITHUB_ENV

    - uses: actions-rs/cargo@v1
      with:
        command: test
