name: Main

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    name: cargo build and test
    env:
      CARGO: cargo
      TARGET:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - linux-stable
        - linux-32bit-stable
        - linux-beta
        - linux-nightly
        - macos-stable
        - win-msvc-stable
        - win-gnu-stable
        include:
        - build: linux-stable
          os: ubuntu-latest
          rust: stable
          use_cross: False
        - build: linux-32bit-stable
          os: ubuntu-latest
          rust: stable
          target: i686-unknown-linux-gnu
          use_cross: True
        - build: linux-beta
          os: ubuntu-latest
          rust: beta
          use_cross: False
        - build: linux-nightly
          os: ubuntu-latest
          rust: nightly
          use_cross: False
        - build: macos-stable
          os: macos-latest
          rust: stable
          use_cross: False
        - build: win-msvc-stable
          os: windows-latest
          rust: stable
          use_cross: False
        - build: win-gnu-stable
          os: windows-latest
          rust: stable-x86_64-gnu
          use_cross: False
    steps:

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --target ${{ matrix.target }}

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: test
        args: --target ${{ matrix.target }}

    - name: cargo build --no-default-features
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --target ${{ matrix.target }} --no-default-features

    - name: cargo test --no-default-features
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: test
        args: --target ${{ matrix.target }} --no-default-features
